require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }

require_relative 'lib/capistrano/git_strategy'
require_relative 'lib/capistrano/log_invocations'

LogInvocations.enable
