source 'https://rubygems.org'

gem 'rails', '~> 4.0'
gem 'sqlite3'
gem 'protected_attributes'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2',       '~>0.3'
gem 'authlogic',    :git => 'git://github.com/binarylogic/authlogic.git', :ref => 'abc0997'
gem 'paperclip',    '~>3.3'
gem 'delayed_job',  '~>4.0'
gem 'delayed_job_active_record', '~>4.0'
gem 'redis',        '~>3.0'
gem 'hiredis',      '~>0.4'
gem 'daemons',      '~>1.1'
gem 'json',         '~>1.7'
gem 'aws-sdk',      '~>1.9'
gem 'oauth',        '~>0.4'
gem 'acts-as-taggable-on', '~>2.4'
gem 'unf',          '~>0.1'
gem 'mustache',     '~>0.99'
gem 'highline'

group :development do
  gem 'thin'
  gem 'fog'
  gem 'wirble'
  gem 'what_methods'
  # gem 'tracer_bullet'
  gem 'quiet_assets'
  gem 'capistrano',         '~> 3.1',  require: false
  gem 'capistrano-rails',   '~> 1.1',  require: false
end

group :test do
  gem 'mocha', :require => false
  gem 'turn'
  gem 'openkit', :path => File.expand_path('../../clients/ruby', __FILE__)
  gem 'factory_girl'
end

group :development, :test do
  gem 'byebug'
end

gem 'sass-rails',   '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', :platforms => :ruby

# Still needed?
#gem 'turbo-sprockets-rails3'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'

# To use debugger
# gem 'debugger'
