#!/usr/bin/env ruby

require 'rest-client'
require 'json'
require 'pp'
require 'debugger'

APP_KEY = "QBQ7ebzX3SymLZPQxbBR"

def yes?(x)
  print x + " (y/n) "
  gets.chomp == "y"
end

class OKApi

  def initialize(app_key, endpoint, json_data = nil)
    @app_key = app_key
    @endpoint = endpoint
    @json_data = json_data || {}
  end

  def post
    j = @json_data.merge(:app_key => @app_key)
    RestClient.post @endpoint,
                    j.to_json,
                    :content_type => :json,
                    :accept => :json
  end

  def get
    j = { :params => @json_data.merge({:app_key => @app_key}),
          :content_type => :json,
          :accept => :json }
    RestClient.get @endpoint, j
  end
end

print "Which leaderboard id?"
x = OKApi.new(APP_KEY,
              "http://localhost:3000/leaderboards",
              nil)
pp JSON.parse(x.get())
leaderboard_id = gets.chomp.to_i

if yes?("Find or create a user?")
  print "Enter nick: "
  nick = gets.chomp
  print "Enter fb_id: "
  fb_id = gets.chomp.to_i
  x = OKApi.new(APP_KEY, "http://localhost:3000/users", {:user => {:fb_id => fb_id, :nick => nick}})
  res = JSON.parse(x.post())
  pp res

  if yes?("Post score for user #{res['id']}?")
    print "Enter score: "
    score = gets.chomp.to_i



    x = OKApi.new(APP_KEY,
                  "http://localhost:3000/scores",
                  {:score => {:leaderboard_id => leaderboard_id, :user_id => res['id'], :value => score}})
    res = x.post()
    pp res
  end
end


if yes?("Get scores?")
  x = OKApi.new(APP_KEY, "http://localhost:3000/scores", {:leaderboard_id => leaderboard_id})
  res = x.get()
  pp JSON.parse(res)
end
